go_import_path: github.com/codedellemc/libstorage

language: go

# the order below is important as the first value is grok'd by the
# Makefile as the default version of Go used to build the project
go:
  - 1.8.3

os:
  - linux

jobs:
  include:
    - stage: build
      env: TRAVIS_GOARCH=amd64 COVERAGE_ENABLED=1
      before_install:
        - export GOARCH="${TRAVIS_GOARCH:-amd64}"
        - go env
        - if [ "$COVERAGE_ENABLED" = "1" ] && [ "$TRAVIS_GO_VERSION" = "$COVERED_GO_VERSION" ]; then echo coverage enabled; fi
        - git config --global 'url.https://gopkg.in/yaml.v1.insteadof' 'https://gopkg.in/yaml.v1/'
        - git config --global 'url.https://gopkg.in/yaml.v2.insteadof' 'https://gopkg.in/yaml.v2/'
        - git config --global 'url.https://gopkg.in/fsnotify.v1.insteadof' 'https://gopkg.in/fsnotify.v1/'
        - git config --global 'url.https://github.com/.insteadof' 'git://github.com/'
        - git config --global 'url.https://github.com/.insteadof' 'git@github.com:'
        - make -C api version
        - make vendor
      script: make -j build
    - stage: docker-plugins
      sudo: required
      script: echo "build docker plug-ins"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
